import { Word } from './word';

export const WORDS: Word[] = [
  new Word('的', '的', 'de5', 'de', "indicates possession, like adding 's to a noun"),
  new Word('我', '我', 'wo3', 'wǒ', 'I; me'),
  new Word('你', '你', 'ni3', 'nǐ', 'you (singular)'),
  new Word('是', '是', 'shi4', 'shì', 'be; is; are; am'),
  new Word('了', '了', 'le5', 'le', 'indicates a completed or finished action'),
  new Word('不', '不', 'bu4', 'bù', 'no; not'),
  new Word('在', '在', 'zai4', 'zài', 'at; on; in; indicates an action in progress'),
  new Word('他', '他', 'ta1', 'tā', 'he; him'),
  new Word('我们', '我們', 'wo3men5', 'wǒmen', 'we; us'),
  new Word('好', '好', 'hao3', 'hǎo', 'good'),
  new Word('有', '有', 'you3', 'yǒu', 'have'),
  new Word('这', '這', 'zhe4', 'zhè', 'this'),
  new Word('会', '會', 'hui4', 'huì', 'know how to'),
  new Word('吗', '嗎', 'ma5', 'ma', 'indicates a yes/no question (added to a statement)'),
  new Word('什么', '什麼', 'shen2me5', 'shénme', 'what? (replaces the noun to turn a statement into a question)'),
  new Word('说', '說', 'shuo1', 'shuō', 'speak'),
  new Word('她', '她', 'ta1', 'tā', 'she'),
  new Word('想', '想', 'xiang3', 'xiǎng', 'think; believe; suppose; would like to'),
  new Word('一', '一', 'yi1', 'yī', 'one; once; a'),
  new Word('很', '很', 'hen3', 'hěn', 'very; quite'),
  new Word('人', '人', 'ren2', 'rén', 'person; man; people'),
  new Word('那', '那', 'na4', 'nà', 'that; then'),
  new Word('来', '來', 'lai2', 'lái', 'come; arrive; ever since; next'),
  new Word('都', '都', 'dou1', 'dōu', 'all; both'),
  new Word('个', '個', 'ge5', 'ge', 'general measure word'),
  new Word('能', '能', 'neng2', 'néng', 'can; be able'),
  new Word('去', '去', 'qu4', 'qù', 'go; to leave'),
  new Word('和', '和', 'he2', 'hé', 'and; with'),
  new Word('做', '做', 'zuo4', 'zuò', 'do; make'),
  new Word('上', '上', 'shang4', 'shàng', 'above; up'),
  new Word('没有', '沒有', 'mei2you3', 'méiyǒu', 'not have; there is not'),
  new Word('看', '看', 'kan4', 'kàn', 'see; look at; to watch'),
  new Word('怎么', '怎麼', 'zen3me5', 'zěnme', 'how?'),
  new Word('现在', '現在', 'xian4zai4', 'xiànzài', 'now'),
  new Word('点', '點', 'dian3', 'diǎn', "a dot; a little; o'clock"),
  new Word('呢', '呢', 'ne5', 'ne', 'indicates a question; how about...?;'),
  new Word('太', '太', 'tai4', 'tài', 'too (much)'),
  new Word('里', '裡', 'li3', 'lǐ', 'inside; Chinese mile (~.5 km)'),
  new Word('听', '聽', 'ting1', 'tīng', 'listen; hear'),
  new Word('谁', '誰', 'shei2', 'shéi', 'who'),
  new Word('多', '多', 'duo1', 'duō', 'many'),
  new Word('时候', '時候', 'shi2hou5', 'shíhou', 'time'),
  new Word('下', '下', 'xia4', 'xià', 'fall; below'),
  new Word('谢谢', '謝謝', 'xie4xie5', 'xièxie', 'thank you'),
  new Word('先生', '先生', 'xian1sheng5', 'xiānsheng', 'Mr.; Sir'),
  new Word('喜欢', '喜歡', 'xi3huan5', 'xǐhuan', 'to like'),
  new Word('大', '大', 'da4', 'dà, dài', 'big; large'),
  new Word('东西', '東西', 'dong1xi5', 'dōngxi', 'things; stuff'),
  new Word('小', '小', 'xiao3', 'xiǎo', 'small; young'),
  new Word('叫', '叫', 'jiao4', 'jiào', 'to be called'),
  new Word('爱', '愛', 'ai4', 'ài', 'love'),
  new Word('年', '年', 'nian2', 'nián', 'year'),
  new Word('请', '請', 'qing3', 'qǐng', 'please; invite; to treat someone to something'),
  new Word('回', '回', 'hui2', 'huí', 'to return; to reply; to go back'),
  new Word('工作', '工作', 'gong1zuo4', 'gōngzuò', 'work; a job'),
  new Word('钱', '錢', 'qian2', 'qián', 'money; coin'),
  new Word('吃', '吃', 'chi1', 'chī', 'eat'),
  new Word('开', '開', 'kai1', 'kāi', 'to open; to start; to operate (a vehicle)'),
  new Word('家', '家', 'jia1', 'jiā', 'family; home'),
  new Word('哪', '哪', 'na3', 'nǎa', 'which; how'),
  new Word('朋友', '朋友', 'peng2you5', 'péngyou', 'friend'),
  new Word('妈妈', '媽媽', 'ma1ma5', 'māma', 'mom; mum'),
  new Word('今天', '今天', 'jin1tian1', 'jīntiān', 'today'),
  new Word('几', '幾', 'ji3', 'jǐ', 'how many; several; a few'),
  new Word('爸爸', '爸爸', 'ba4ba5', 'bàba', 'Dad'),
  new Word('些', '些', 'xie1', 'xiē', 'some; few; several'),
  new Word('怎么样', '怎麼樣', 'zen3me5yang4', 'zěnmeyàng', 'how about?; how is/was it?'),
  new Word('对不起', '對不起', 'dui4bu5qi3', 'duìbuqǐ', 'sorry'),
  new Word('住', '住', 'zhu4', 'zhù', 'to live; reside; to stop'),
  new Word('三', '三', 'san1', 'sān', 'three'),
  new Word('高兴', '高興', 'gao1xing4', 'gāoxìng', 'happy; glad'),
  new Word('买', '買', 'mai3', 'mǎi', 'to buy'),
  new Word('医生', '醫生', 'yi1sheng1', 'yīshēng', 'doctor'),
  new Word('哪儿', '哪兒', 'na3r5', 'nǎr', 'where? (Beijing accent)'),
  new Word('字', '字', 'zi4', 'zì', 'letter; character'),
  new Word('名字', '名字', 'ming2zi5', 'míngzi', 'name'),
  new Word('认识', '認識', 'ren4shi5', 'rènshi', 'recognize; know (a person)'),
  new Word('坐', '坐', 'zuo4', 'zuò', 'sit'),
  new Word('喝', '喝', 'he1', 'hē', 'to drink'),
  new Word('写', '寫', 'xie3', 'xiě', 'to write; to compose'),
  new Word('月', '月', 'yue4', 'yuè', 'moon; month; flesh (radical)'),
  new Word('号', '號', 'hao4', 'hào', 'number; day of a month'),
  new Word('狗', '狗', 'gou3', 'gǒu', 'dog'),
  new Word('岁', '歲', 'sui4', 'suì', 'years old; age'),
  new Word('看见', '看見', 'kan4jian4', 'kànjiàn', 'see; catch sight of'),
  new Word('打电话', '打電話', 'da3 dian4hua4', 'dǎ diànhuà', 'make a phone call'),
  new Word('喂', '喂', 'wei4', 'wèi', 'hello (on the phone)'),
  new Word('儿子', '兒子', 'er2zi5', 'érzi', 'son'),
  new Word('漂亮', '漂亮', 'piao4liang5', 'piàoliang', 'pretty; beautiful'),
  new Word('分钟', '分鐘', 'fen1zhong1', 'fēnzhōng', 'minute; (measure word for time)'),
  new Word('再见', '再見', 'zai4jian4', 'zàijiàn', 'goodbye; see you later'),
  new Word('本', '本', 'ben3', 'běn', 'measure word for books'),
  new Word('明天', '明天', 'ming2tian1', 'míngtiān', 'tomorrow'),
  new Word('少', '少', 'shao3', 'shǎo', 'few; little'),
  new Word('多少', '多少', 'duo1shao5', 'duōshao', 'how much?; how many?'),
  new Word('块', '塊', 'kuai4', 'kuài', 'lump; piece; sum of money'),
  new Word('女儿', '女兒', "nv3'er2", "nǚ'ér", 'daughter'),
  new Word('小姐', '小姐', 'xiao3jie5', 'xiǎojie', 'young lady; miss; Ms.'),
  new Word('衣服', '衣服', 'yi1fu5', 'yīfu', 'clothes'),
  new Word('水', '水', 'shui3', 'shuǐ', 'water'),
  new Word('学校', '學校', 'xue2xiao4', 'xuéxiào', 'school'),
  new Word('电影', '電影', 'dian4ying3', 'diànyǐng', 'movie; film'),
  new Word('书', '書', 'shu1', 'shū', 'book; letter'),
  new Word('四', '四', 'si4', 'sì', 'four'),
  new Word('五', '五', 'wu3', 'wǔ', 'five'),
  new Word('医院', '醫院', 'yi1yuan4', 'yīyuàn', 'hospital'),
  new Word('没关系', '沒關系', 'mei2 guan1xi5', 'méi guānxi', "it doesn't matter; never mind"),
  new Word('飞机', '飛機', 'fei1ji1', 'fēijī', 'airplane'),
  new Word('二', '二', 'er4', 'èr', 'two'),
  new Word('电视', '電視', 'dian4shi4', 'diànshì', 'television; TV'),
  new Word('读', '讀', 'du2', 'dú', 'to read; to study'),
  new Word('后面', '后面', 'hou4mian5', 'hòumian', 'back; behind'),
  new Word('昨天', '昨天', 'zuo2tian1', 'zuótiān', 'yesterday'),
  new Word('睡觉', '睡覺', 'shui4 jiao4', 'shuì jiào', 'to sleep; go to bed'),
  new Word('六', '六', 'liu4', 'liù', 'six'),
  new Word('老师', '老師', 'lao3shi1', 'lǎoshī', 'teacher'),
  new Word('星期', '星期', 'xing1qi1', 'xīngqī', 'week'),
  new Word('十', '十', 'shi2', 'shí', 'ten'),
  new Word('猫', '貓', 'mao1', 'māo', 'cat'),
  new Word('电脑', '電腦', 'dian4nao3', 'diànnǎo', 'computer'),
  new Word('热', '熱', 're4', 'rè', 'heat; hot'),
  new Word('学生', '學生', 'xue2sheng5', 'xuésheng', 'student'),
  new Word('下午', '下午', 'xia4wu3', 'xiàwǔ', 'afternoon'),
  new Word('学习', '學習', 'xue2xi2', 'xuéxí', 'learn; to study'),
  new Word('冷', '冷', 'leng3', 'lěng', 'cold'),
  new Word('不客气', '不客氣', 'bu2 ke4qi5', 'bú kèqi', "you're welcome; don't be polite"),
  new Word('前面', '前面', 'qian2mian4', 'qiánmiàn', 'in front'),
  new Word('八', '八', 'ba1', 'bā', 'eight'),
  new Word('中国', '中國', 'Zhong1guo2', 'Zhōngguó', 'China'),
  new Word('七', '七', 'qi1', 'qī', 'seven'),
  new Word('菜', '菜', 'cai4', 'cài', 'dish (type of food); vegetables'),
  new Word('桌子', '桌子', 'zhuo1zi5', 'zhuōzi', 'table; desk'),
  new Word('出租车', '出租車', 'chu1zu1che1', 'chūzūchē', 'taxi; cab'),
  new Word('天气', '天氣', 'tian1qi4', 'tiānqì', 'weather'),
  new Word('茶', '茶', 'cha2', 'chá', 'tea'),
  new Word('九', '九', 'jiu3', 'jiǔ', 'nine'),
  new Word('商店', '商店', 'shang1dian4', 'shāngdiàn', 'shop; store'),
  new Word('椅子', '椅子', 'yi3zi5', 'yǐzi', 'chair'),
  new Word('同学', '同學', 'tong2xue2', 'tóngxué', 'fellow student; schoolmate'),
  new Word('一点儿', '一點兒', 'yi4dian3r5', 'yìdiǎnr', 'a bit; a few'),
  new Word('苹果', '蘋果', 'ping2guo3', 'píngguǒ', 'apple'),
  new Word('饭店', '飯店', 'fan4dian4', 'fàndiàn', 'restaurant; hotel'),
  new Word('中午', '中午', 'zhong1wu3', 'zhōngwǔ', 'noon; midday'),
  new Word('上午', '上午', 'shang4wu3', 'shàngwǔ', 'late morning (before noon)'),
  new Word('水果', '水果', 'shui3guo3', 'shuǐguǒ', 'fruit'),
  new Word('杯子', '杯子', 'bei1zi5', 'bēizi', 'cup; glass'),
  new Word('下雨', '下雨', 'xia4yu3', 'xiàyǔ', 'to rain'),
  new Word('米饭', '米飯', 'mi3fan4', 'mǐfàn', '(cooked) rice'),
  new Word('北京', '北京', 'Bei3jing1', 'Běijīng', 'Beijing'),
  new Word('汉语', '漢語', 'Han4yu3', 'Hànyǔ', 'Chinese language'),
];
